services:
  - type: web
    name: chess-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./docs/backend/chess.Dockerfile
    dockerContext: ./docs/backend/
    dockerCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    healthCheckPath: /health
    autoDeploy: true

    envVars:
      - key: CORS_ORIGINS
        value: https://liorvi35.github.io
      - key: BORDER_SIZE
        value: "16"
      - key: WATERMARK_TEXT
        value: boardClassification
      # Optional, but fine:
      - key: PYTHONUNBUFFERED
        value: "1"
